//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFT_Trade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetrievingCollection
    {
        public int Id { get; set; }
        public Nullable<float> one_day_volume { get; set; }
        public Nullable<float> one_day_change { get; set; }
        public Nullable<float> one_day_sales { get; set; }
        public Nullable<float> one_day_average_price { get; set; }
        public Nullable<float> seven_day_volume { get; set; }
        public Nullable<float> seven_day_change { get; set; }
        public Nullable<float> seven_day_sales { get; set; }
        public Nullable<float> seven_day_average_price { get; set; }
        public Nullable<float> thirty_day_volume { get; set; }
        public Nullable<float> thirty_day_change { get; set; }
        public Nullable<float> thirty_day_sales { get; set; }
        public Nullable<float> thirty_day_average_price { get; set; }
        public Nullable<float> total_volume { get; set; }
        public Nullable<float> total_sales { get; set; }
        public Nullable<float> total_supply { get; set; }
        public Nullable<float> count { get; set; }
        public Nullable<int> num_owners { get; set; }
        public Nullable<float> average_price { get; set; }
        public Nullable<int> num_reports { get; set; }
        public Nullable<float> market_cap { get; set; }
        public Nullable<int> floor_price { get; set; }
        public string banner_image_url { get; set; }
        public string featured_image_url { get; set; }
        public string image_url { get; set; }
        public string large_image_url { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public string telegram_url { get; set; }
        public string twitter_username { get; set; }
        public string instagram_username { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
